name: DeployCICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: npm build
        run: |
          npm install
          npm run build
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: '-avz --delete'
          SOURCE: 'dist/'
          REMOTE_HOST: '39.96.191.139'
          REMOTE_USER: 'root'
          TARGET: '/var/www/test'
